{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "검색어를 입력해주세요: 클라뷰여배우크림\n"
     ]
    }
   ],
   "source": [
    "##### Data Type No.2: Naver SearchAd #####\n",
    "    #a. 네이버 키워드 일일검색량 (ex. 네이버_키워드_일일검색량_2019-07-04.csv)\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import time\n",
    "import os\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.common.exceptions import NoSuchElementException\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from datetime import date, datetime, timedelta\n",
    "from pytz import timezone\n",
    "\n",
    "try:\n",
    "    os.remove(\"/Users/danie1ryu/Downloads/datalab.xlsx\")\n",
    "except FileNotFoundError: \n",
    "    pass\n",
    "\n",
    "file_download_path = '/Users/danie1ryu/Downloads/'\n",
    "file_save_path = '/Users/danie1ryu/Downloads/'\n",
    "chromedriver_path = '/Users/danie1ryu/Desktop/chromedriver'\n",
    "\n",
    "naver_id = 'onrikorea'\n",
    "naver_pw = 'onrikorea00!'\n",
    "keyword = input(\"검색어를 입력해주세요: \")\n",
    "\n",
    "    \n",
    "today = datetime.now(timezone('Asia/Seoul'))\n",
    "yesterday = today - timedelta(1)\n",
    "yesterday_period = '.'.join(yesterday.strftime(\"%Y-%m-%d %H:%M:%S\").split(' ')[0].split('-'))\n",
    "yesterday_hyphen = yesterday.strftime(\"%Y-%m-%d %H:%M:%S\").split(' ')[0]\n",
    "\n",
    "browser = webdriver.Chrome(chromedriver_path)\n",
    "browser.get('https://datalab.naver.com/keyword/trendSearch.naver')\n",
    "browser.find_element_by_xpath('//*[@id=\"lnb\"]/div/ul/li[3]/a').send_keys(Keys.RETURN)\n",
    "browser.find_element_by_id('item_keyword1').send_keys(keyword)\n",
    "\n",
    "time.sleep(4)\n",
    "\n",
    "browser.find_element_by_xpath('//*[@id=\"content\"]/div/div[2]/div[1]/div/form/fieldset/div/div[6]/div[1]/label[2]').click()\n",
    "\n",
    "time.sleep(3)\n",
    "\n",
    "#모바일 & PC 전체 검색량 옵션 클릭\n",
    "browser.find_element_by_xpath('//*[@id=\"item_device_0\"]').click()\n",
    "\n",
    "time.sleep(3)\n",
    "browser.find_element_by_xpath('//*[@id=\"content\"]/div/div[2]/div[1]/div/form/fieldset/a/span').click()\n",
    "\n",
    "time.sleep(5)\n",
    "\n",
    "#엑셀 파일 다운로드\n",
    "browser.find_element_by_xpath('//*[@id=\"content\"]/div/div[1]/div[1]/div/div/div/div/div/div[1]/div[4]/a').send_keys(Keys.RETURN)\n",
    "\n",
    "time.sleep(3)\n",
    "\n",
    "#browser.close()  \n",
    "\n",
    "browser.get('https://searchad.naver.com/login?returnUrl=https:%2F%2Fmanage.searchad.naver.com%2Fcustomers%2F1519222%2Ftool%2Fkeyword-planner')\n",
    "browser.find_element_by_id('uid').send_keys(naver_id)\n",
    "browser.find_element_by_id('upw').send_keys(naver_pw)\n",
    "browser.find_element_by_xpath('//*[@id=\"container\"]/div/div/fieldset/div/span/button').send_keys(Keys.RETURN)\n",
    "\n",
    "browser.get('https://manage.searchad.naver.com/customers/1519222/tool/keyword-planner?keywords=')\n",
    "\n",
    "browser.find_element_by_xpath('/html/body/elena-root/elena-wrap/div/div[2]/elena-tool-wrap/div/div/div/div/elena-keyword-planner/div[2]/div[1]/div[1]/div[2]/div/div/div[1]/div/textarea').send_keys(keyword)\n",
    "browser.find_element_by_xpath('/html/body/elena-root/elena-wrap/div/div[2]/elena-tool-wrap/div/div/div/div/elena-keyword-planner/div[2]/div[1]/div[1]/div[3]/button').send_keys(Keys.RETURN)\n",
    "\n",
    "time.sleep(5)\n",
    "\n",
    "try:\n",
    "    PC_monthly_search_traffic = int(''.join(browser.find_element_by_css_selector('#wgt-{} > td.elenaColumn-monthlyPcQcCnt > div > span'.format(keyword)).text.split(',')))\n",
    "except ValueError:\n",
    "    PC_monthly_search_traffic = 0\n",
    "    \n",
    "\n",
    "try:\n",
    "    Mobile_monthly_search_traffic = int(''.join(browser.find_element_by_css_selector('#wgt-{} > td.elenaColumn-monthlyMobileQcCnt > div > span'.format(keyword)).text.split(',')))\n",
    "except ValueError:\n",
    "    Mobile_monthly_search_traffic = 0\n",
    "    \n",
    "    \n",
    "total_monthly_search_traffic = PC_monthly_search_traffic + Mobile_monthly_search_traffic\n",
    "\n",
    "browser.close()\n",
    "\n",
    "df_total = pd.read_excel(file_download_path + 'datalab.xlsx', header=None).loc[7:]\n",
    "\n",
    "df_total['키워드'] = keyword\n",
    "\n",
    "#df_total['일일검색량'] = ''\n",
    "\n",
    "df_total.rename(columns={0:'날짜',\n",
    "                      1:'Proportion(%)'}, \n",
    "                 inplace=True)\n",
    "\n",
    "df_total.loc[7:, 'Proportion(%)'] = pd.to_numeric(df_total.loc[7:, 'Proportion(%)'])\n",
    "\n",
    "total_prop_total = df_total['Proportion(%)'].sum()\n",
    "df_total['일일검색량'] = df_total['Proportion(%)'] / total_prop_total * total_monthly_search_traffic\n",
    "\n",
    "\n",
    "df_total['일일검색량'] = df_total['일일검색량'].astype(int)\n",
    "\n",
    "\n",
    "df_total = df_total.drop('Proportion(%)', axis=1)\n",
    "\n",
    "df_total = df_total.set_index('날짜')\n",
    "\n",
    "#df_total.to_csv(file_save_path + keyword + '_키워드검색량_' + yesterday_hyphen + '.csv', header=True)\n",
    "df_total.to_excel(file_save_path + keyword + '_키워드검색량_' + yesterday_hyphen + '.xlsx', header=True)\n",
    "                "
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "                                                                                                                                                          "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
